name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    services:
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: root
          POSTGRES_USER: root
          POSTGRES_DB: mycontacts
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      api:
        image: ghcr.io/fabioseixas/api-js-ci-end2end:latest
        ports:
          - 3001:3001

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     registry: dockerhub (??)
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: fabioseixas
          password: ${{ secrets.GH_TOKEN_FABIO }}

      - name: Install dependencies
        run:
          npm install

      - name: Run migrations
        run: node ./bk_migrations.js

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run start
